# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Train', models.IntegerField()),
                ('From', models.CharField(max_length=10)),
                ('To', models.CharField(max_length=10)),
                ('Offset', models.TimeField()),
            ],
        ),
    ]
