# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-05 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltable',
            name='Leaving_Time',
            field=models.TimeField(default='1:00'),
        ),
        migrations.AlterField(
            model_name='traveltable',
            name='Offset',
            field=models.TimeField(default='0:10'),
        ),
    ]
