# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-06 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshare', '0002_auto_20170505_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltable',
            name='Leaving_Date',
            field=models.DateField(default=datetime.date(2017, 5, 6)),
        ),
        migrations.AlterField(
            model_name='traveltable',
            name='Leaving_Time',
            field=models.TimeField(),
        ),
    ]
