# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-06 12:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshare', '0003_auto_20170506_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltable',
            name='Lower_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 6, 12, 12, 6, 463946)),
        ),
        migrations.AddField(
            model_name='traveltable',
            name='Upper_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 6, 12, 12, 6, 463986)),
        ),
    ]
