# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-06 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshare', '0004_auto_20170506_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltable',
            name='Lower_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 6, 13, 7, 32, 381546)),
        ),
        migrations.AlterField(
            model_name='traveltable',
            name='Upper_Time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 6, 13, 7, 32, 381585)),
        ),
    ]
